server:
  port: 4001

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: login_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:4000          #匹配后提供服务的路由地址
          uri: lb://authority-server #匹配后提供服务的路由地址
          predicates:
              - Path=/logintest        # 断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
    nacos:
      server-addr: localhost:8848
  application:
    name: gateway-server