server:
  port: 4001

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: login_routh             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://authority-server  #匹配后提供服务的路由地址
          predicates:
              - Path=/login       # 断言，路径相匹配的进行路由
              - Method=POST
        - id: home_routh             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://authority-server  #匹配后提供服务的路由地址
          predicates:
              - Path=/home       # 断言，路径相匹配的进行路由
              - Method=POST
        - id: menu_routh             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://authority-server  #匹配后提供服务的路由地址
          predicates:
              - Path=/menu/getMenuList       # 断言，路径相匹配的进行路由
              - Method=Get
        - id: user_routh
          uri: lb://authority-server
          predicates:
              - Path=/user/getUserList
              - Method=Get
      discovery:
        locator:
          enabled: true

      #设置全局跨域，虽然我设置了没用
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
    nacos:
      server-addr: localhost:8848
  application:
    name: gateway-server