server:
  port: 4003

spring:
  application:
    name: user-server

  #开启热部署
  devtools:
    restart:
      enabled: true

  #配置mysql数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name:  com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: hyx2215

  #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#配置 mybatis-plus
mybatis-plus:
  mapper-locations:  classpath:mapper/*.xml
  #开启 SQL 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

moudle:
  name: authority